### ISSUE TITLE
Sequencer loop behavior

### ISSUE THREAD

**Issue by rghvdberg** [zynayumi/zynayumi#5]
While implementing and testing the UI I found the SEQ_LOOP behaves a bit strange and I'm wondering if this is the intended behavior.
I've set up a sequence of 4 notes (0,1,2,3)
Here's what I found :
`||: :||` means , repeating
```
seq end = 4

seq loop = 0
steps played:  ||:0 1 2 3:||

seq loop = 1
steps played: 0 1 2 3 , 2 3 , ||: 1 2 3 :||

seq loop = 2 
steps played: 0 1 2 3 ||:2 3:||

seq loop = 3 
steps played:0 1 2 3... (3 holds ...)

seq loop = 4
steps played:0 1 2 3 , 1...
```

**Comment by ngeiswei** [comment]
Looks like a bug, thanks for your report, @rghvdberg.  I'll look into it next week.

In the mean time I wanted to ask, do you think I should add a *repeat mode* parameter with the following values:
1. Off
2. Forward
3. Pingpong
as opposed to being systematically forward?

**Comment by ngeiswei** [comment]
@alcomposer, what do you think about the *repeat mode* parameter suggested above?

**Comment by alcomposer** [comment]
@ngeiswei having a look at a few established synths like: https://www.plogue.com/products/chipsounds.html looks like there isn't a loop direction setting. However Zynayumi's sequencer feels like it's double timing as an aroeggiator as well.

Is the sequencer in Zynayumi part of the original emulation?

Saying all this, I do think pingpong could be cool, maybe:

* Forward
* Backward
* Pingpong
* Random

**Comment by ngeiswei** [comment]
> Is the sequencer in Zynayumi part of the original emulation?

No.  But it is implemented in several YM2149 trackers.  I took inspiration from Arkos Tracker 2.

> Random

Random?  You're on fire, dude, excellent idea.  I'm busy these days/weeks, do you think you could implement those?  Otherwise, fear not, I will take care of it, it's just that it's gonna take a while.

> possibly these modes could be scheduled for Zynayumi 1.x?

Almost nobody is using Zynayumi at the moment, so I think we can still break backward compatibility at this point.

**Comment by ngeiswei** [comment]
@alcomposer, I've decided to quickly add the user parameters for now, so that you can move forward with supporting it in the GUI.  Then when I get more time I'll implement it (as well as fixing the bug raised in that issue).

**Comment by ngeiswei** [comment]
@alcomposer, I've added the sequential mode parameter, see https://github.com/zynayumi/libzynayumi/blob/08d8e30b916efce3865bcfbc83468d009b600f4a/src/zynayumi/patch.hpp#L213-L221 which I (or you, or someone else) can implement later.
